name: Flake8 check

on:
  pull_request:
    branches:
      - main

jobs:
  flake8:
    name: Flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install flake8
      - name: Run Flake8
        run: flake8